name: bccm_core
description: Contains core functionality, etc
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_links: ^6.3.2
  auto_route: ^9.2.2
  clock: ^1.1.1
  connectivity_plus: ^6.0.5
  device_info_plus: ^11.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  flutter:
    sdk: flutter
  flutter_appauth: ^7.0.1
  flutter_hooks: ^0.20.5
  flutter_image: ^4.1.10
  flutter_local_notifications: ^17.2.3
  flutter_riverpod: ^2.5.3
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^8.0.3
  responsive_framework: ^1.5.1
  riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  rudder_sdk_flutter: ^3.0.0
  rudder_sdk_flutter_platform_interface: ^3.0.0
  shared_preferences: ^2.3.2
  synchronized: ^3.3.0+3
  universal_io: ^2.2.2
  unleash_proxy_client_flutter: ^1.5.3
  url_launcher: ^6.3.1
  vibration: ^2.0.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.16.0
  share_plus: ^10.0.3
  hooks_riverpod: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  graphql_codegen: ^1.0.1
  flutter_appauth_platform_interface: ^7.0.1

dependency_overrides:
  js: ^0.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
